#!/usr/bin/env bash

iDIR="$HOME/.config/mako/icons"

# Get brightness
get_backlight() {
	LIGHT=$(printf "%.0f\n" $(brightnessctl g))
	echo "${LIGHT}"
}

# Get percentage of the brightness
get_percentage() {
	max=$(brightnessctl max)
	twenty_percent=$((max * 20 / 100))
	current="$(get_backlight)"
	
	PERCENT=$(printf "%.0f\n" $((current / twenty_percent * 20)))
	echo "${PERCENT}"
}

# Get icons
get_icon() {
	current="$(get_percentage)"
	
	if [[ ("$current" -eq "0") ]]; then
		icon="$iDIR/brightness-20.png"
	elif [[ ("$current" -eq "20") ]]; then
		icon="$iDIR/brightness-40.png"
	elif [[ ("$current" -eq "40") ]]; then
		icon="$iDIR/brightness-60.png"
	elif [[ ("$current" -eq "60") ]]; then
		icon="$iDIR/brightness-80.png"
	else
		icon="$iDIR/brightness-100.png"
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $(get_percentage)%"
}

# Increase brightness
inc_backlight() {
	brightnessctl s +5% && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl s 5%- && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_backlight
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
