#!/bin/bash

sleep 3

WALLPAPER_DIR="$HOME/wallpapers/"

# Get the name of connected monitors with hyprctl
mapfile -t monitors < <(hyprctl monitors -j | jq -r '.[] | .name')
n=${#monitors[@]}

# Get random wallpapers
WALLPAPERS=$
mapfile -t wallpapers < <((find "$WALLPAPER_DIR" -type f | shuf -n "$n"))

# Apply the selected wallpaper
for ((i=0; i<n; i++)); do
	monitor="${monitors[$i]}"
	wallpaper="${wallpapers[$i]}"

	hyprctl hyprpaper wallpaper "$monitor","$wallpaper"
done
